trigger:
  branches:
    include:
      - main

variables:
  DEPLOYMENT_NAMESPACE: "windows-aks-ns-devops"
  AZURE_CONTAINER_REGISTRY: "akswindemoreg.azurecr.io"
  CONTAINER_NAME: "windows-container-app"
  CONTAINER_TAG: "v1"
  IMAGE_FULL_PATH: "$(AZURE_CONTAINER_REGISTRY)/$(CONTAINER_NAME):$(CONTAINER_TAG)"
  AKS_CLUSTER_NAME: "demowinclu001"  # replace with your actual AKS name
  RESOURCE_GROUP: "rg-apps-passmig-asia-v-santanup-demo"  # replace with your actual resource group

pool:
  vmImage: 'windows-2022'

stages:
- stage: Deploy
  displayName: Deploy Windows Container to AKS
  jobs:
  - job: DeployJob
    displayName: Deploy to AKS
    steps:

    - task: AzureCLI@2
      displayName: 'Login to Azure and ACR'
      inputs:
        azureSubscription: 'aks-windows-demo-panchsan-sc'  # your Azure RM connection
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show
          az acr login --name $(AZURE_CONTAINER_REGISTRY)

    - task: AzureCLI@2
      displayName: 'Set AKS Context and Create Namespace (if not exists)'
      inputs:
        azureSubscription: 'aks-windows-demo-panchsan-sc'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --name $(AKS_CLUSTER_NAME) --resource-group $(RESOURCE_GROUP) --overwrite-existing
          kubectl apply -f Deployments/00-windows-namespace.yaml --validate=false

    - task: KubernetesManifest@1
      name: DeployToAks
      displayName: 'Deploy Windows Web App'
      inputs:
        action: deploy
        kubernetesServiceConnection: 'demowinclu001-aks-windows-ado-ns'
        namespace: $(DEPLOYMENT_NAMESPACE)
        manifests: |
          Deployments/01-windows-deployment.yaml
          Deployments/02-windows-service.yaml
        containers: |
          $(IMAGE_FULL_PATH)

    - task: Kubernetes@1
      displayName: 'Wait for Deployment Rollout'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'demowinclu001-aks-windows-ado-ns'
        namespace: $(DEPLOYMENT_NAMESPACE)
        command: rollout
        arguments: 'status deployment/windows-webapp'