trigger:
  branches:
    include:
      - main

variables:
  DEPLOYMENT_NAMESPACE: "my-windows-aks-ns"
  AZURE_CONTAINER_REGISTRY: "akswindemoreg.azurecr.io"
  CONTAINER_NAME: "windows-container-app"
  CONTAINER_TAG: "v1"
  IMAGE_FULL_PATH: "$(AZURE_CONTAINER_REGISTRY)/$(CONTAINER_NAME):$(CONTAINER_TAG)"

pool:
  vmImage: 'windows-2022'

stages:
- stage: Deploy
  displayName: Deploy Windows Container to AKS
  jobs:
  - job: DeployJob
    displayName: Deploy to AKS
    steps:

    - task: AzureCLI@2
      displayName: 'Login to Azure and ACR'
      inputs:
        azureSubscription: 'aks-windows-demo-panchsan-sc' # Azure RM connection
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show
          az acr login --name $(AZURE_CONTAINER_REGISTRY)

    # Create namespace if not exists
    - task: Kubernetes@1
      displayName: 'Create Namespace (if not exists)'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'demowinclu001-aks-windows-ado-ns'
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: $(DEPLOYMENT_NAMESPACE)

    # Deploy manifest files with image substitution
    - task: KubernetesManifest@1
      name: DeployToAks
      displayName: 'Deploy Windows Web App'
      inputs:
        action: deploy
        kubernetesServiceConnection: 'demowinclu001-aks-windows-ado-ns'
        namespace: $(DEPLOYMENT_NAMESPACE)
        manifests: |
          Deployments/01-windows-deployment.yaml
          Deployments/02-windows-service.yaml
        containers: |
          $(IMAGE_FULL_PATH)

    # Wait for rollout to complete
    - task: Kubernetes@1
      displayName: 'Wait for Deployment Rollout'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'demowinclu001-aks-windows-ado-ns'
        namespace: $(DEPLOYMENT_NAMESPACE)
        command: rollout
        arguments: 'status deployment/windows-webapp'