trigger:
  branches:
    include:
      - main

variables:
  # Set your values here
  ACR_NAME: 'akswindemoreg'
  IMAGE_NAME: 'windows-container-app'
  IMAGE_TAG: 'v1'
  IMAGE_FULL_PATH: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)'
  K8S_NAMESPACE: 'my-windows-aks-ns'

pool:
  vmImage: 'windows-2022'

stages:
- stage: Deploy
  displayName: Deploy Windows App to AKS
  jobs:
  - job: DeployJob
    displayName: Deploy to AKS
    steps:
    - task: Checkout@1

    # Optional: Ensure ACR login (for later image validation/debug)
    - task: AzureCLI@2
      displayName: 'Login to Azure and ACR'
      inputs:
        azureSubscription: 'aks-windows-demo-panchsan-sc'  # Azure RM service connection
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(ACR_NAME)

    # Ensure namespace exists
    - task: Kubernetes@1
      displayName: 'Create Namespace if Not Exists'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'demowinclu001-aks-windows-ado-ns' # Kubernestes service connection
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: $(K8S_NAMESPACE)

    # Deploy manifests (deployment + service)
    - task: KubernetesManifest@1
      name: DeployToAKS
      displayName: 'Deploy Windows Deployment & Service'
      inputs:
        kubernetesServiceConnection: 'demowinclu001-aks-windows-ado-ns' # Kubernestes service connection
        namespace: $(K8S_NAMESPACE)
        manifests: |
          Deployment/windows-deployment.yaml
          Deployment/windows-service.yaml
        containers: |
          $(IMAGE_FULL_PATH)

    # Optional: Wait for rollout to complete
    - task: Kubernetes@1
      displayName: 'Wait for Deployment Rollout'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'demowinclu001-aks-windows-ado-ns' # Kubernestes service connection
        namespace: $(K8S_NAMESPACE)
        command: 'custom'
        arguments: 'rollout status deployment/windows-deployment'