trigger:
  branches:
    include:
      - main

variables:
  DEPLOYMENT_NAMESPACE: "windows-aks-ns-devops"
  AZURE_CONTAINER_REGISTRY: "akswindemoreg.azurecr.io"
  CONTAINER_NAME: "windows-container-app"
  CONTAINER_TAG: "v1"
  IMAGE_FULL_PATH: "$(AZURE_CONTAINER_REGISTRY)/$(CONTAINER_NAME):$(CONTAINER_TAG)"

  AKS_CLUSTER_NAME: "demowinclu001"
  AKS_RESOURCE_GROUP: "rg-apps-passmig-asia-v-santanup-demo"

  AZURE_SUBSCRIPTION: "aks-windows-demo-panchsan-sc" # Azure RM Service Connection
  KUBE_SERVICE_CONNECTION: "demowinclu001-aks-windows-ado-ns" # Kubernetes Service Connection

pool:
  vmImage: 'windows-2022'

stages:
- stage: Deploy
  displayName: Deploy Windows Container to AKS
  jobs:
  - job: DeployJob
    displayName: Deploy to AKS
    steps:

    # Step 1: Install kubectl if not present
    - task: KubectlInstaller@0
      displayName: 'Install kubectl'
      inputs:
        kubectlVersion: 'latest'

    # Step 2: Login to Azure and ACR
    - task: AzureCLI@2
      displayName: 'Login to Azure and ACR'
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging into Azure"
          az acr login --name $(AZURE_CONTAINER_REGISTRY)

    # Step 3: Set AKS context and create namespace if missing
    - task: AzureCLI@2
      displayName: 'Set AKS Context & Create Namespace'
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Setting AKS context..."
          az aks get-credentials --resource-group $(AKS_RESOURCE_GROUP) --name $(AKS_CLUSTER_NAME) --overwrite-existing

          echo "Checking/Creating Namespace: $(DEPLOYMENT_NAMESPACE)"
          kubectl get namespace $(DEPLOYMENT_NAMESPACE) || kubectl create namespace $(DEPLOYMENT_NAMESPACE)

    # Step 4: Deploy manifests with image substitution
    - task: KubernetesManifest@1
      displayName: 'Deploy Windows Web App'
      inputs:
        action: deploy
        kubernetesServiceConnection: $(KUBE_SERVICE_CONNECTION)
        namespace: $(DEPLOYMENT_NAMESPACE)
        manifests: |
          Deployments/01-windows-deployment.yaml
          Deployments/02-windows-service.yaml
        containers: |
          $(IMAGE_FULL_PATH)

    # Step 5: Wait for rollout to complete
    - task: Kubernetes@1
      displayName: 'Wait for Deployment Rollout'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(KUBE_SERVICE_CONNECTION)
        namespace: $(DEPLOYMENT_NAMESPACE)
        command: rollout
        arguments: 'status deployment/windows-webapp'