name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "akswindemoreg"
  CONTAINER_NAME: "windows-container-app"
  RESOURCE_GROUP: "rg-apps-passmig-asia-v-santanup-demo"
  CLUSTER_NAME: "demowinclu001"
  DEPLOYMENT_NAMESPACE: "my-windows-aks-ns"

jobs:
  DeployWindowsContainertoAKS:
    permissions:
      contents: read
      id-token: write
    runs-on: windows-2022
    environment: development

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    - name: Build with MSBuild
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" WindowsApp.sln /p:Configuration=Release

    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push image to ACR
      run: |
        az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .

    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    - name: Create namespace if not exists
      run: |
        kubectl get namespace ${{ env.DEPLOYMENT_NAMESPACE }} || kubectl create namespace ${{ env.DEPLOYMENT_NAMESPACE }}

    - name: Deploy application to AKS
      uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        namespace: ${{ env.DEPLOYMENT_NAMESPACE }}
        manifests: |
          Deployments/windows-deployment.yaml
          Deployments/windows-service.yaml
        images: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
